### ISSUE TITLE
Issue with extra semicolon and quotes on bootstrap-solarized-dark.less

### ISSUE THREAD

**Issue by cchamberlain** [aalpern/bootstrap-solarized#1]
Glad to see someone put this together.  I found an error on line 76 of bootstrap-solarized-dark.less.

This is what it is now:
@headings-font-family: HelveticaNeue-CondensedBold","Helvetica Neue","Arial Narrow, Arial, sans-serif;;

This is what I think its supposed to be:
@headings-font-family: "HelveticaNeue-CondensedBold","Helvetica Neue","Arial Narrow", Arial, sans-serif;

**Comment by aalpern** [comment]
Just merged the PR - thanks!

**Comment by cchamberlain** [comment]
Awesome and NP!  Was happy to find these styles as they were very useful for an internal portal.
